FROM alpine:3.16

ENV \
	LC_ALL=en_US.UTF-8 \
	LANG=en_US.UTF-8 \
	LANGUAGE=en_US.UTF-8

RUN \
	apk add --no-cache \
		build-base \
		py3-pip \
		python3 \
		python3-dev && \
	python3 -m ensurepip && \
	pip install \
		aiohttp==3.8.3

COPY ecs-credentials.py /

CMD ["python3", "/ecs-credentials.py"]
