FROM debian:bullseye

ENV \
	LC_ALL=en_US.UTF-8 \
	LANG=en_US.UTF-8 \
	LANGUAGE=en_US.UTF-8

RUN \
	apt-get update && \
	apt-get install -y \
		python3 \
	    python3-dev \
	    python3-pip \
	    wget && \
	pip install \
		coverage==4.5.3 && \
	wget -O mc https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2022-11-07T23-47-39Z && \
	chmod +x mc

COPY LICENSE README.md mobius3.py setup.py test.py test_with_coverage.sh .coveragerc /
